server:
  port: 3000

spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
    mongodb:
      uri: mongodb://localhost:27017/engine
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8